### ISSUE TITLE
Getting an error when trying to install.

### ISSUE THREAD

**Issue by rmathew1973** [tpisto/pdf-fill-form#1]
I've followed the instructions for installation and I'm receiving the following error

Russells-MacBook-Air:affiliation russell$ npm install pdf-fill-form --save
\
> pdf-fill-form@1.0.2 install /Users/russell/Projects/affiliation/node_modules/pdf-fill-form
> node-gyp rebuild

  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
../src/NodePoppler.cc:9:10: fatal error: 'poppler/qt4/poppler-form.h' file not
      found
#include <poppler/qt4/poppler-form.h>
         ^
1 error generated.
make: *** [Release/obj.target/pdf_fill_form/src/NodePoppler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/russell/Projects/affiliation/node_modules/pdf-fill-form
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "pdf-fill-form" "--save"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! pdf-fill-form@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdf-fill-form@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pdf-fill-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdf-fill-form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/russell/Projects/affiliation/npm-debug.log

**Comment by rmathew1973** [comment]
I've temporarily fixed this by editing the NodePoppler.cc file to refer to the header files directly for popper and cairo
