### ISSUE TITLE
issue installing module in node 0.12.7

### ISSUE THREAD

**Issue by wassimsalib** [tpisto/pdf-fill-form#10]
Hi, I was trying to install the module through npm on Linux precise 64, and I got the following errors:

../src/NodePoppler.cc: In function 'QBuffer* writePdfFields(WriteFieldsParams)':
../src/NodePoppler.cc:191:26: error: 'class Poppler::FormFieldChoice' has no member named 'setEditChoice'
make: *** [Release/obj.target/pdf_fill_form/src/NodePoppler.o] Error 1
make: Leaving directory `/var/tmp/sharpone/node_modules/pdf-fill-form/build'

**Comment by muhammadghazali** [comment]
I was having similar problem, after trial and error several times.

Here is the npm log when tried to install it with node v0.10.40 and npm v1.4.28:

```
sudo npm uninstall pdf-fill-form && sudo npm install pdf-fill-form
unbuild pdf-fill-form@1.1.0
npm WARN package.json connect-redis@1.4.5 No repository field.
npm WARN engine pdf-fill-form@1.1.0: wanted: {"node":">=0.11.14"} (current: {"node":"0.10.40","npm":"1.4.28"})
\
> pdf-fill-form@1.1.0 install /vagrant/sharpOne_app/node_modules/pdf-fill-form
> node-gyp rebuild

make: Entering directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
make: Warning: File `pdf_fill_form.target.mk' has modification time 0.0031 s in the future
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:0:
../src/NodePoppler.h:21:39: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                       ^
../src/NodePoppler.h:21:43: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                           ^
../src/NodePoppler.h:21:63: error: expected ‘,’ or ‘...’ before ‘<’ token
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                                               ^
make: *** [Release/obj.target/pdf_fill_form/src/pdf-fill-form.o] Error 1
make: Leaving directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-65-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/sharpOne_app/node_modules/pdf-fill-form
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! pdf-fill-form@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdf-fill-form@1.1.0 install script.
npm ERR! This is most likely a problem with the pdf-fill-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdf-fill-form
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-65-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdf-fill-form"
npm ERR! cwd /vagrant/sharpOne_app
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Here is the installation log when I'm using node v0.10.40 and npm v2.14.6:

```
sudo npm install -g npm@2.14.6
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.6 /usr/local/lib/node_modules/npm
vagrant@vagrant-ubuntu-trusty-64:/vagrant/sharpOne_app$  sudo npm uninstall pdf-fill-form && sudo npm install pdf-fill-form
npm WARN uninstall not installed in /vagrant/sharpOne_app/node_modules: "pdf-fill-form"
npm WARN engine pdf-fill-form@1.1.0: wanted: {"node":">=0.11.14"} (current: {"node":"0.10.40","npm":"2.14.6"})
\
> pdf-fill-form@1.1.0 install /vagrant/sharpOne_app/node_modules/pdf-fill-form
> node-gyp rebuild

make: Entering directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:0:
../src/NodePoppler.h:21:39: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                       ^
../src/NodePoppler.h:21:43: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                           ^
../src/NodePoppler.h:21:63: error: expected ‘,’ or ‘...’ before ‘<’ token
 WriteFieldsParams v8ParamsToCpp(const v8::FunctionCallbackInfo<v8::Value>& args);
                                                               ^
make: *** [Release/obj.target/pdf_fill_form/src/pdf-fill-form.o] Error 1
make: Leaving directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-65-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/sharpOne_app/node_modules/pdf-fill-form
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "pdf-fill-form"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE

npm ERR! pdf-fill-form@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdf-fill-form@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pdf-fill-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdf-fill-form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/sharpOne_app/npm-debug.log
```

And then I tried to install it using node v0.12.7 and npm v2.14.6, as the pdf-fill-form required node higher than 0.11.4:

```
sudo npm install pdf-fill-form
\
> pdf-fill-form@1.1.0 install /vagrant/sharpOne_app/node_modules/pdf-fill-form
> node-gyp rebuild

make: Entering directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
make: Warning: File `pdf_fill_form.target.mk' has modification time 0.00099 s in the future
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
  SOLINK_MODULE(target) Release/obj.target/pdf_fill_form.node
  COPY Release/pdf_fill_form.node
make: warning:  Clock skew detected.  Your build may be incomplete.
make: Leaving directory `/vagrant/sharpOne_app/node_modules/pdf-fill-form/build'
pdf-fill-form@1.1.0 node_modules/pdf-fill-form
└── nan@1.7.0
```

Its was build successfuly, and change the node environment to node v0.10.40, but when tried to run the app, its failed:

```
[Error: /vagrant/sharpOne_app/node_modules/pdf-fill-form/build/Release/pdf_fill_form.node: undefined symbol: node_module_register]

module.js:340
    throw err;
    ^
Error: Cannot find module '/vagrant/sharpOne_app/node_modules/pdf-fill-form/lib/../build/default/pdf_fill_form'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /vagrant/sharpOne_app/node_modules/pdf-fill-form/lib/pdf-fill-form.js:47:39
    at Object.<anonymous> (/vagrant/sharpOne_app/node_modules/pdf-fill-form/lib/pdf-fill-form.js:49:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/sharpOne_app/api/services/PrestigeQuoteService.js:6:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /vagrant/sharpOne_app/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/vagrant/sharpOne_app/node_modules/include-all/index.js:44:9)
```

Any thoughts? @tpisto

**Comment by bobjohnbob** [comment]
I had the same problem as the OP.  It turned out to be due to using an old version of libPoppler provided by an old-ish version of ubunto.  I used Ubuntu 14.04 instead of 12.04 and it had a new enough version of libPoppler.  Just make sure you're using new than version 0.22, either by upgrading your distro or manually installing it.
