### ISSUE TITLE
Fatal error on npm install: 'poppler/qt4/poppler-form.h' file not found

### ISSUE THREAD

**Issue by humhann** [tpisto/pdf-fill-form#17]
I get this error when trying to `npm install pdf-fill-form`

-------------------------------------------------
pdf-fill-form@2.0.0 install /Users/.../node_modules/pdf-fill-form
node-gyp rebuild

  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
../src/NodePoppler.cc:9:10: fatal error: 'poppler/qt4/poppler-form.h' file not
      found
#include <poppler/qt4/poppler-form.h>
         ^
1 error generated.
make: *** [Release/obj.target/pdf_fill_form/src/NodePoppler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

-------------------------------------------------

I am using:

OS X El Capitan 10.11.5
NodeJS v4.5.0
npm 2.15.9

Dependencies installed using `brew install qt4 cairo poppler --with-qt4`. Same error occured before and after these installed.

**Comment by humhann** [comment]
I see now this is a duplicate of an already solved issue, worked for me too: https://github.com/tpisto/pdf-fill-form/issues/16
