### ISSUE TITLE
NodePoppler error

### ISSUE THREAD

**Issue by florianbepunkt** [tpisto/pdf-fill-form#40]
I have a docker container based on debian:jessie image with the necessary libraries installed as in your instructions. npm install fails with the following errors:

> pdf-fill-form@3.2.0 install /var/www/app/current/node_modules/pdf-fill-form
> node-gyp rebuild

```
make: Entering directory '/var/www/app/current/node_modules/pdf-fill-form/build'
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
../src/NodePoppler.cc: In function 'QBuffer* writePdfFields(WriteFieldsParams)':
../src/NodePoppler.cc:265:16: error: 'formFields' was not declared in this scope
     qDeleteAll(formFields);
                ^
../src/NodePoppler.cc:266:12: error: 'page' was not declared in this scope
     delete page;
            ^
../src/NodePoppler.cc: At global scope:
../src/NodePoppler.cc:271:3: error: 'bufferDevice' does not name a type
   bufferDevice->open(QIODevice::ReadWrite);
   ^
../src/NodePoppler.cc:274:3: error: expected unqualified-id before 'if'
   if (params.saveFormat == "imgpdf") {
   ^
../src/NodePoppler.cc:277:3: error: expected unqualified-id before 'else'
   else {
   ^
../src/NodePoppler.cc:281:3: error: expected unqualified-id before 'delete'
   delete document;
   ^
../src/NodePoppler.cc:283:3: error: expected unqualified-id before 'return'
   return bufferDevice;
   ^
../src/NodePoppler.cc:284:1: error: expected declaration before '}' token
 }
 ^
../src/NodePoppler.cc: In function 'QBuffer* writePdfFields(WriteFieldsParams)':
../src/NodePoppler.cc:267:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
pdf_fill_form.target.mk:118: recipe for target 'Release/obj.target/pdf_fill_form/src/NodePoppler.o' failed
make: Leaving directory '/var/www/app/current/node_modules/pdf-fill-form/build'
make: *** [Release/obj.target/pdf_fill_form/src/NodePoppler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.27-moby
gyp ERR! command "/usr/local/nvm/versions/node/v6.10.2/bin/node" "/usr/local/nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/app/current/node_modules/pdf-fill-form
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
cm-jarvis@1.0.0 /var/ww
```

**Comment by florianbepunkt** [comment]
Also on mac, the install fails with your new version...I had it previously working, but installing the new version from npm I get the following error.

not sure if both cases are linked but I would guess so. Could you please update the install docs?

```
> node-gyp rebuild

2017-05-24 17:32:17.260 xcodebuild[1942:225563] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-05-24 17:32:17.261 xcodebuild[1942:225563] Failed to load plugin at: /Users/floriannorbertbepunkt/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:
../src/NodePoppler.h:5:10: fatal error: 'QtCore/QBuffer' file not found
#include <QtCore/QBuffer>
```

**Comment by gatodeveloper** [comment]
@florianbepunkt I think that the latest merge on master has an error

I don't see tags versions :(

for now, you can use a specific commit 

It works for me.

https://github.com/tpisto/pdf-fill-form/commit/bacbf8d1ed31fe8dc805c933e92aebb6fc223c00

Change your package file with:

```
"pdf-fill-form": "git://github.com/tpisto/pdf-fill-form.git#bacbf8d1ed31fe8dc805c933e92aebb6fc223c00"
```

**Comment by florianbepunkt** [comment]
@gatodeveloper Thank you. I can confirm... the latest merge has a bug.

But I have another interesting error: Filling the pdf on my mac works fine. Running the same app inside my docker container works except that € signs in my form field become fi ligatures.

**Comment by tpisto** [comment]
I have now published 3.2.1 that should fix this. Please report if not.

**Comment by gatodeveloper** [comment]
Thanks @tpisto, Works for me.

**Comment by florianbepunkt** [comment]
@tpisto Confirmed. It's fixed. Thank you.
