### ISSUE TITLE
ctime error no member named 'clock' in the global namespace

### ISSUE THREAD

**Issue by Sigura** [tpisto/pdf-fill-form#61]
> node -v && npm -v
v8.12.0
6.4.1
> xcode-select -v
xcode-select version 2354

OSX 10.14.1 Mojave

```
> git clone git@github.com:tpisto/pdf-fill-form.git
> cd pdf-fill-form
> npm i


> pdf-fill-form@4.1.0 install /Users/.../work/pdf-fill-form
> node-gyp rebuild

  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:
In file included from ../src/NodePoppler.h:5:
In file included from /usr/local/include/QtCore/QBuffer:1:
In file included from /usr/local/include/QtCore/qbuffer.h:43:
In file included from /usr/local/include/QtCore/qiodevice.h:43:
In file included from /usr/local/include/QtCore/qglobal.h:1201:
In file included from /usr/local/include/QtCore/qglobalstatic.h:100:
In file included from /usr/local/include/QtCore/qmutex.h:48:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:60:9: error: no member named 'clock' in the global namespace; did you mean 'flock'?
using ::clock;
      ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/fcntl.h:528:5: note: 'flock' declared here
int     flock(int, int);
        ^
In file included from ../src/pdf-fill-form.cc:2:
In file included from ../src/NodePoppler.h:5:
In file included from /usr/local/include/QtCore/QBuffer:1:
In file included from /usr/local/include/QtCore/qbuffer.h:43:
In file included from /usr/local/include/QtCore/qiodevice.h:43:
In file included from /usr/local/include/QtCore/qglobal.h:1201:
In file included from /usr/local/include/QtCore/qglobalstatic.h:100:
In file included from /usr/local/include/QtCore/qmutex.h:48:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:61:9: error: no member named 'difftime' in the global namespace
using ::difftime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:62:9: error: no member named 'mktime' in the global namespace; did you mean 'mktemp'?
using ::mktime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/stdlib.h:216:7: note: 'mktemp' declared here
char    *mktemp(char *);
         ^
In file included from ../src/pdf-fill-form.cc:2:
In file included from ../src/NodePoppler.h:5:
In file included from /usr/local/include/QtCore/QBuffer:1:
In file included from /usr/local/include/QtCore/qbuffer.h:43:
In file included from /usr/local/include/QtCore/qiodevice.h:43:
In file included from /usr/local/include/QtCore/qglobal.h:1201:
In file included from /usr/local/include/QtCore/qglobalstatic.h:100:
In file included from /usr/local/include/QtCore/qmutex.h:48:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:63:9: error: no member named 'time' in the global namespace
using ::time;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:65:9: error: no member named 'asctime' in the global namespace
using ::asctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:66:9: error: no member named 'ctime' in the global namespace
using ::ctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:67:9: error: no member named 'gmtime' in the global namespace
using ::gmtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:68:9: error: no member named 'localtime' in the global namespace
using ::localtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:70:9: error: no member named 'strftime' in the global namespace
using ::strftime;
      ~~^
9 errors generated.
make: *** [Release/obj.target/pdf_fill_form/src/pdf-fill-form.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@8/8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node@8/8.12.0/bin/node" "/usr/local/Cellar/node@8/8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/.../work/pdf-fill-form
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdf-fill-form@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdf-fill-form@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-11-09T15_36_19_351Z-debug.log

```

**Comment by Sigura** [comment]
saw #23 it does not solve it

**Comment by Sigura** [comment]
maybe because brew does not support it now: `brew linkapps qt5`?

**Comment by Sigura** [comment]
solution:

1. remove xcode from application
2. `brew doctor`, then remove all warnings
3. `brew reinstall qt5 cairo poppler --with-qt`
```
export LDFLAGS="-L/usr/local/opt/qt/lib" &&                                                                                                                                                                                  
export CPPFLAGS="-I/usr/local/opt/qt/include" &&
export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
```

I don't know why, but it works now without `xcode-select --install`
