### ISSUE TITLE
Node 12 support?

### ISSUE THREAD

**Issue by ionizer** [tpisto/pdf-fill-form#73]
I have been trying Node 12 for a while after it becomes active LTS and been using this library for a project. But whenever I try to install this library using Node 12, I get these logging below:

<details>
  <summary>node-gyp errors (click to expand)</summary>

  <p>

  ```
ionizer@ion-ubuntu-vm0:~/Documents/playground/pdf-filling$ yarn add pdf-fill-form
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | linux | x64
gyp info find Python using Python version 2.7.15 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/ionizer/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ionizer/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ionizer/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ionizer/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/ionizer/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ionizer/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form/build'
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
../src/NodePopplerAsync.cc: In member function ‘virtual void PdfWriteWorker::HandleOKCallback()’:
../src/NodePopplerAsync.cc:47:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(2, argv);
                             ^
In file included from ../src/NodePopplerAsync.cc:1:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
../src/NodePoppler.cc: In function ‘WriteFieldsParams v8ParamsToCpp(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/NodePoppler.cc:215:62: error: no matching function for call to ‘v8::Value::ToString()’
   String::Utf8Value sourcePdfFileNameParam(args[0]->ToString());
                                                              ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:218:50: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> changeFields = args[1]->ToObject();
                                                  ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:227:36: error: no matching function for call to ‘v8::Value::ToObject()’
     parameters = args[2]->ToObject();
                                    ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:231:50: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
       String::Utf8Value saveFormatParam(saveParam);
                                                  ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note:   candidate expects 2 arguments, 1 provided
../src/NodePoppler.cc:237:39: error: no matching function for call to ‘v8::Value::Int32Value()’
       nCores = coresParam->Int32Value();
                                       ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2613:40: note: candidate: v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/NodePoppler.cc:242:46: error: no matching function for call to ‘v8::Value::NumberValue()’
       scale_factor = scaleParam->NumberValue();
                                              ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2608:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2608:39: note:   candidate expects 1 argument, 0 provided
../src/NodePoppler.cc:247:51: error: no matching function for call to ‘v8::Value::BooleanValue()’
       antialiasing = antialiasParam->BooleanValue();
                                                   ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2603:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2603:8: note:   candidate expects 1 argument, 0 provided
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2606:51: note: candidate: v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:2606:51: note:   candidate expects 1 argument, 0 provided
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:252:60: error: no matching function for call to ‘v8::Object::GetPropertyNames()’
   Local<Array> fieldArray = changeFields->GetPropertyNames();
                                                            ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3567:43: note: candidate: v8::MaybeLocal<v8::Array> v8::Object::GetPropertyNames(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                           ^~~~~~~~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3567:43: note:   candidate expects 1 argument, 0 provided
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3569:43: note: candidate: v8::MaybeLocal<v8::Array> v8::Object::GetPropertyNames(v8::Local<v8::Context>, v8::KeyCollectionMode, v8::PropertyFilter, v8::IndexFilter, v8::KeyConversionMode)
   V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                           ^~~~~~~~~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3569:43: note:   candidate expects 5 arguments, 0 provided
../src/NodePoppler.cc:254:42: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     Local<Value> name = fieldArray->Get(i);
                                          ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3461:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
                                                   ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:255:48: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     Local<Value> value = changeFields->Get(name);
                                                ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/NodePoppler.cc:256:47: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
     fields[std::string(*String::Utf8Value(name))] = std::string(*String::Utf8Value(value));
                                               ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note:   candidate expects 2 arguments, 1 provided
../src/NodePoppler.cc:256:89: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
     fields[std::string(*String::Utf8Value(name))] = std::string(*String::Utf8Value(value));
                                                                                         ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note:   candidate expects 2 arguments, 1 provided
../src/NodePoppler.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE ReadSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/NodePoppler.cc:486:38: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         fieldArray->Set(fieldNum, obj);
                                      ^
In file included from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/ionizer/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/NodePoppler.cc:1:
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8.h:3412:22: note: declared here
                 bool Set(uint32_t index, Local<Value> value));
                      ^
/home/ionizer/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
pdf_fill_form.target.mk:137: recipe for target 'Release/obj.target/pdf_fill_form/src/NodePoppler.o' failed
make: Leaving directory '/home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form/build'
make: *** [Release/obj.target/pdf_fill_form/src/NodePoppler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ionizer/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/home/ionizer/.nvm/versions/node/v12.13.0/bin/node" "/home/ionizer/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ionizer/Documents/playground/pdf-filling/node_modules/pdf-fill-form
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
  ```

  </p>
</details>

How can we support Node 12?

**Comment by tpisto** [comment]
Hi! Sorry to hear that you have troubles installing this in Node 12. Last time @florianbepunkt made the Node 10 compatibility, so would be great to hear from him if he has this already working with Node 12. If not, it would be great if you could have some time to investigate this issue. We use https://github.com/nodejs/nan library for node version compatibility. Problem could be solved just by upgrading NAN library doing with some minor migrations.

**Comment by florianbepunkt** [comment]
I'll try and have a look on the weekend, pretty swamped this week…

**Comment by ionizer** [comment]
Hello there, it's been a month. I think I can make a fork to try and upgrade the nan library, but I'm not sure what exactly are the changes do we need :/

**Comment by florianbepunkt** [comment]
@tpisto: I refactored NodePoppler.cc in order to make it compile in Node 13. Since I basically have no knowledge of c++, I'm not sure whether I broke something. And my code might read completely bananas for a c++ experienced developer.

Shall I open a PR and you have a look? Is there a test suite I can use to check whether I messed something up?

**Comment by tpisto** [comment]
@florianbepunkt Wonderful! Please make a PR. Idea of this repo is to Get Pdf Done... not to attend to some C++ beauty contest :) As far as that GPD principle is fulfilled, we all are super happy for any progress. Thank you for your contribution!

**Comment by tpisto** [comment]
@florianbepunkt Thank you for your contribution!  🎉
