### ISSUE TITLE
Can't compile on Heroku

### ISSUE THREAD

**Issue by lveronese** [tpisto/pdf-fill-form#83]
Hi,
I'm trying to build an application on Heroku using pdf-fill-form.
I get an error during the build process (this error does not occur on my development machine)
This is what I get:

remote:        > pdf-fill-form@5.0.1 install /tmp/build_6faac3c6a4e982414b8205ff32942c87/node_modules/pdf-fill-form
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory '/tmp/build_6faac3c6a4e982414b8205ff32942c87/node_modules/pdf-fill-form/build'
remote:          CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
remote:          CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
remote:          CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
remote:        ../src/NodePoppler.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE ReadBufferSync(Nan::NAN_METHOD_ARGS_TYPE)’:
remote:        ../src/NodePoppler.cc:539:7: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
remote:           int n = 0;
remote:               ^
remote:        ../src/NodePoppler.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE ReadSync(Nan::NAN_METHOD_ARGS_TYPE)’:
remote:        ../src/NodePoppler.cc:565:7: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
remote:           int n = 0;
remote:               ^
remote:          SOLINK_MODULE(target) Release/obj.target/pdf_fill_form.node
remote:        /usr/bin/ld: /tmp/build_6faac3c6a4e982414b8205ff32942c87/.apt/usr/lib/x86_64-linux-gnu/libcairo.a(cairo-boxes.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
remote:        /usr/bin/ld: final link failed: Bad value
remote:        collect2: error: ld returned 1 exit status
remote:        pdf_fill_form.target.mk:170: recipe for target 'Release/obj.target/pdf_fill_form.node' failed
remote:        make: *** [Release/obj.target/pdf_fill_form.node] Error 1
remote:        make: Leaving directory '/tmp/build_6faac3c6a4e982414b8205ff32942c87/node_modules/pdf-fill-form/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_6faac3c6a4e982414b8205ff32942c87/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
remote:        gyp ERR! System Linux 4.4.0-1057-aws
remote:        gyp ERR! command "/tmp/build_6faac3c6a4e982414b8205ff32942c87/.heroku/node/bin/node" "/tmp/build_6faac3c6a4e982414b8205ff32942c87/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_6faac3c6a4e982414b8205ff32942c87/node_modules/pdf-fill-form
remote:        gyp ERR! node -v v12.13.1
remote:        gyp ERR! node-gyp -v v5.0.5
remote:        gyp ERR! not ok 
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! pdf-fill-form@5.0.1 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the pdf-fill-form@5.0.1 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.04Wb6/_logs/2020-01-29T20_44_14_273Z-debug.log
remote: 
remote: -----> Build failed

It is a linker error. If you can help me in any way it will be appreciated.

Thank you.

**Comment by telenc** [comment]
+1

**Comment by satyajitnayk** [comment]
+1
